#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend servers
        bind :80
        default_backend webservers
backend webservers
        balance roundrobin
        server 148073-web-01 52.87.153.4:80 check
        server 148073-web-02 100.25.137.85:80 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart
